// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2Yx2vea9BiXlQcnO12_wNhcvntSLeF8',
    appId: '1:991204003515:web:99294c0719d082c57d239e',
    messagingSenderId: '991204003515',
    projectId: 'quiz-app-cdbc1',
    authDomain: 'quiz-app-cdbc1.firebaseapp.com',
    storageBucket: 'quiz-app-cdbc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72Hc340XiAbM5wBzi5Sm18rtRQg33ZNw',
    appId: '1:991204003515:android:e52692a1257ed77f7d239e',
    messagingSenderId: '991204003515',
    projectId: 'quiz-app-cdbc1',
    storageBucket: 'quiz-app-cdbc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Y8_7zdMyyojckIyLjy-v0IU1D67H8Vo',
    appId: '1:991204003515:ios:2cd7a954f7cf6e1d7d239e',
    messagingSenderId: '991204003515',
    projectId: 'quiz-app-cdbc1',
    storageBucket: 'quiz-app-cdbc1.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Y8_7zdMyyojckIyLjy-v0IU1D67H8Vo',
    appId: '1:991204003515:ios:2cd7a954f7cf6e1d7d239e',
    messagingSenderId: '991204003515',
    projectId: 'quiz-app-cdbc1',
    storageBucket: 'quiz-app-cdbc1.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy2Yx2vea9BiXlQcnO12_wNhcvntSLeF8',
    appId: '1:991204003515:web:ef1f3d5b61a2f7387d239e',
    messagingSenderId: '991204003515',
    projectId: 'quiz-app-cdbc1',
    authDomain: 'quiz-app-cdbc1.firebaseapp.com',
    storageBucket: 'quiz-app-cdbc1.firebasestorage.app',
  );
}
